# Generated by Django 3.1.2 on 2020-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_bid', models.DateTimeField(auto_now_add=True)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bidder', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_commented', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.FileField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listed_by', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('MU', 'Musical Instruments'), ('SP', 'Sports Equipment'), ('NC', 'No Category Specified')], default='NC', max_length=2)),
                ('end_auction', models.DateTimeField()),
            ],
        ),
    ]
