# Generated by Django 3.1.2 on 2020-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.popsugar.com%2Ftech%2FFunny-Cat-GIFs-35436224&psig=AOvVaw3x3r4d6pWO5qZWMH0fRJs7&ust=1603436420510000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDzjabQx-wCFQAAAAAdAAAAABAD', max_length=2048),
            preserve_default=False,
        ),
    ]
