# Generated by Django 3.1.2 on 2020-10-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201022_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
