# Generated by Django 3.1.2 on 2020-10-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201022_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_auction',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='No Description', max_length=2048),
            preserve_default=False,
        ),
    ]
