# Generated by Django 3.1.2 on 2020-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201026_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('MU', 'Musical Instruments'), ('SP', 'Sports Equipment'), ('NC', 'No Category Specified')], default='NC', max_length=64),
        ),
    ]
