# Generated by Django 3.1.2 on 2020-10-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201026_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(max_length=2048),
        ),
    ]
