# Generated by Django 3.1.2 on 2020-10-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201027_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Musical Instruments', 'Musical Instruments'), ('Sports Equipment', 'Sports Equipment'), ('No Category Specified', 'No Category Specified')], default='No Category Specified', max_length=64),
        ),
    ]
