# Generated by Django 3.1.2 on 2020-10-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201028_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[(1, 'Electronics'), (2, 'Musical Instruments'), (3, 'Sports Equipment'), (4, 'No Category Specified')], default=999, max_length=64),
        ),
    ]
