# Generated by Django 3.1.2 on 2020-10-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201028_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listing_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[(1, 'Electronics'), (2, 'Musical Instruments'), (3, 'Sports Equipment'), (4, 'Toys and Games'), (999, 'No Category Specified')], default=999, max_length=64),
        ),
    ]
