# Generated by Django 3.1.2 on 2020-11-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
